---
- name: This playbook is to create user
  hosts: all
  become: true
  vars_files:
    - user.yml      
  #  vars:
  #  user: modi 
  tasks:
  - name: Creating user {{ user }}     
    user:
      name: "{{ user }}"

